# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - unit_test

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm cache clean --force
      rm -rf node_modules
      rm package--lock.json
      npm run clean
      npm install
      npm run pretest
      npm run test
    displayName: "npm install, run pretest, then test"
